application: jolecule
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /jolecule.js
  static_files: static/jolecule.js
  upload: static/jolecule.js
- url: /screenshot.png
  static_files: static/screenshot.png
  upload: static/screenshot.png
- url: /v3.js
  static_files: static/v3.js
  upload: static/v3.js
- url: /jquery.js
  static_files: static/jquery.js
  upload: static/jquery.js
- url: /jquery.scrollTo.js
  static_files: static/jquery.scrollTo.js
  upload: static/jquery.scrollTo.js
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /styles
  static_dir: styles
- url: /.*
  script: main.py
