application: jolecule-hrd
version: 3
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /js/jolecule.js
  script: gae_server.py
- url: /js
  static_dir: js
  application_readable: js
- url: /images
  static_dir: static
- url: /jolecule.css
  static_files: static/jolecule.css
  upload: static/jolecule.css
- url: /embed-jolecule.css
  static_files: static/embed-jolecule.css
  upload: static/embed-jolecule.css
- url: /.*
  script: gae_server.py
